EStoreWebApp/Entities/Department.cs
namespace HRAPP.Entities;

[Serializable]
public class Department{
    public int Id{get;set;}
    public string Name{get;set;}
    public string Location{get;set;}
}

EStoreWebApp/Entities/Employee.cs
namespace HRAPP.Entities;

[Serializable]
public class Employee{
    public int Id{get;set;}
    public string Name{get;set;}
}

EStoreWebApp/Models/ErrorViewModel.cs
namespace EStoreWebApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

EStoreWebApp/Models/Product.cs
namespace EStoreWebApp.Models;

public class Product{
    public int Id{get;set;}
    public string Title{get;set;}
    public float UnitPrice{get;set;}
    public int Quantity{get;set;}
}

EStoreWebApp/Controllers/AuthController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using EStoreWebApp.Models;

namespace EStoreWebApp.Controllers;

public class AuthController : Controller
{


    [HttpGet]
    public IActionResult SignIn()
    {
        return View();
    }

    [HttpPost]
    public IActionResult SignIn(string uname, string psw)
    {
        if (uname == "ravi" && psw == "seed")
        {
            return RedirectToAction("ProductRegister", "Products", null);
        }
        return View();
    }

    public IActionResult Register()
    {
        return View();
    }

    public IActionResult ChangePassword()
    {
        return View();
    }

}

EStoreWebApp/Controllers/DashboardController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using EStoreWebApp.Models;

namespace EStoreWebApp.Controllers;

public class DashboardController : Controller
{


    [HttpGet]
    public IActionResult Pie()
    {
        return View();

    }
    public IActionResult Bar()
    {
        return View();
    }

    public IActionResult Line(){
        return View();
    }
    
}

EStoreWebApp/Controllers/EmployeesController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using EStoreWebApp.Models;
using   HRAPP.Services;
using HRAPP.Entities;
namespace EStoreWebApp.Controllers;
public class EmployeesController : Controller
{
    private readonly IEmployeeService _svc;
    public EmployeesController(IEmployeeService svc){
        this._svc=svc;
    }

    [HttpGet]
    public IActionResult Index()
    {
        List<Employee> employees=_svc.GetAll();
        ViewData["employees"]=employees;
        return View();
    }
    public IActionResult Details(int id)
    {
        Employee emp=_svc.GetById(id);
        return View();
    }
}

EStoreWebApp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using EStoreWebApp.Models;

namespace EStoreWebApp.Controllers;

public class HomeController : Controller
{
    //HTTP Incomming WebRequest
    //Action Methods
    //Depends on Request Type

    [HttpGet]
    public IActionResult Index()
    {
        return View();

    }
    public IActionResult Privacy()
    {
        return View();
    }

    public IActionResult Aboutus(){
        return View();
    }
    public IActionResult Contact(){
        return View();

    }
    public IActionResult Services(){
        
        return Json(new {Id=45, Name="Mentoring", Company="Transflower"});

    }
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

EStoreWebApp/Controllers/ProductsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using EStoreWebApp.Models;
using EStoreWebApp.Services;

namespace EStoreWebApp.Controllers;

public class ProductsController : Controller
{

    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }
    public IActionResult ProductRegister()
    {
        return View();
    }
    public IActionResult GetAll()
    {
        
        return View();
    }
}

EStoreWebApp/Controllers/ShoppingCartController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using EStoreWebApp.Models;

namespace EStoreWebApp.Controllers;

public class ShoppingCartController : Controller
{
    
    [HttpGet]
    public IActionResult Index()
    {
        return View();

    } 
}

EStoreWebApp/Views/Employees/Index.cshtml
@using HRAPP.Entities;

<h1>Employees List</h1>
<hr/>

@{
List<Employee> employees=(List<Employee>)ViewData["employees"];
    foreach(Employee emp in employees){
        <p>@emp.Name</p>
    }
}

EStoreWebApp/Views/Home/Aboutus.cshtml
<h1>About us </h1>
<hr/>
<p>Transflower Learning Pvt. Ltd.</p>
<p>A Learning Experience</p>
<p>Mentor : Ravi Tambade</p>

EStoreWebApp/Views/Home/Contact.cshtml
<h1>Contact Us</h1>
<hr/>
<p>Transflower Learning Pvt. Ltd</p>
<p>Url: http://www.transflower.in</p>
<p>Email:ravi.tambade@transflower.in</p>
<p>Contact Number:9881735801</p>
<hr/>

<p>Pune, Maharastra, India</p>

EStoreWebApp/Views/Home/Index.cshtml
@using EStoreWebApp.Models;
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Todays Fresh Flower</h1>
    <hr/>
     <img src="/images/Transflower.jpg" width="100" height="100"/>

</div>

EStoreWebApp/Views/Products/ProductRegister.cshtml
<h1 align='Center'>Product details</h1>
<hr/>
<form action="/products/GetAll"  method="get">
  <div class="form-group">
    <label for="id">Product Id:</label>
    <input type="number" class="form-control" id="id">
  </div>
  <div class="form-group">
    <label for="title">Product Name:</label>
    <input type="text" class="form-control" id="title">
  </div>
  <div class="form-group">
    <label for="unitPrice">Unit Price:</label>
    <input type="number" class="form-control" id="unitPrice">
  </div>
  <div class="form-group">
    <label for="quantity">Quantity:</label>
    <input type="number" class="form-control" id="quantity">
  </div>
  <div class="checkbox">
    <label><input type="checkbox"> Remember me</label>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>

@* id title unitprice quantity *@

EStoreWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EStoreWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EStoreWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EStoreWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
                        </li>

                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="SignIn">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EStoreWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>